[workspace]
members = [
    "liquid-staking-cli",
    "liquid-staking-contracts",
]

resolver = "2"

[workspace.dependencies]
cucumber = { version = "0.21.0" }
odra = { version = "2.1.0" }
odra-cli = { version = "2.1.0" }
odra-modules = { version = "2.1.0"}
odra-test = { version = "2.1.0"}
odra-build = { version = "2.1.0"}
odra-bdd = { version = "2.1.0" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
opt-level = "z"
strip = true

[profile.dev.package."*"]
opt-level = 3