[workspace]
members = [
    "liquid-staking-cli",
    "liquid-staking-contracts",
]

resolver = "2"

[workspace.dependencies]
cucumber = { version = "0.21.0" }
#odra = { git = "https://github.com/odradev/odra.git", branch = "feature/casper-2.0" }
#odra-cli = { git = "https://github.com/odradev/odra.git", branch = "feature/casper-2.0" }
#odra-modules = { git = "https://github.com/odradev/odra.git", branch = "feature/casper-2.0" }
#odra-test = { git = "https://github.com/odradev/odra.git", branch = "feature/casper-2.0" }
#odra-build = { git = "https://github.com/odradev/odra.git", branch = "feature/casper-2.0" }
#odra-bdd = { git = "https://github.com/odradev/odra.git", branch = "feature/casper-2.0" }
 odra = { path = "../odra/odra/odra", version = "2.0.0" }
 odra-cli = { path = "../odra/odra/odra-cli", version = "2.0.0" }
 odra-modules = { path = "../odra/odra/modules", version = "2.0.0" }
 odra-test = { path = "../odra/odra/odra-test", version = "2.0.0" }
 odra-build = { path = "../odra/odra/odra-build", version = "2.0.0" }
 odra-bdd = { path = "../odra/odra/odra-bdd", version = "2.0.0" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
opt-level = "z"
strip = true

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
casper-types = { version = "5.0.0", git = "https://github.com/casper-network/casper-node.git", branch = "feat-2.0" }