[package]
name = "liquid-staking-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
odra.workspace = true
odra-modules.workspace = true

[dev-dependencies]
odra-test.workspace = true
odra-bdd.workspace = true
cucumber.workspace = true

[build-dependencies]
odra-build.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
odra-build.workspace = true

[features]
csv-report = []

[[bin]]
name = "liquid_staking_contracts_build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "liquid-staking-contracts_build_schema"
path = "bin/build_schema.rs"
test = false
#
#[[test]]
#name = "test_staking"
#harness = false
#
#[[test]]
#name = "test_pool"
#harness = false
#
#[[test]]
#name = "test_fee"
#harness = false
#
#[[test]]
#name = "test_validators"
#harness = false
#
#[[test]]
#name = "test_restaking"
#harness = false
#
#[[test]]
#name = "test_bugs"
#harness = false

[[test]]
name = "test_audit"
harness = false
